module.exports = {
	base: require("./lib/components/base.js").base,
	button: require("./lib/components/button"),
	card: require("./lib/components/card.js").card,
	container: require("./lib/components/container.js").container,
	content: require("./lib/components/content.js").content,
	description: require("./lib/components/description.js").description,
	dimmer: require("./lib/components/dimmer.js").dimmer,
	divider: require("./lib/components/divider.js").divider,
	form: require("./lib/components/form"),
	grid: require("./lib/components/grid"),
	header: require("./lib/components/header.js").header,
	icon: require("./lib/components/icon.js").icon,
	image: require("./lib/components/image.js").image,
	label: require("./lib/components/label.js").label,
	menu: require("./lib/components/menu"),
	message: require("./lib/components/message.js").message,
	meta: require("./lib/components/meta.js").meta,
	modal: require("./lib/components/modal"),
	pusher: require("./lib/components/pusher.js").pusher,
	segment: require("./lib/components/segment"),
	sidebar: require("./lib/components/sidebar.js").sidebar,
	step: require("./lib/components/step"),
	subHeader: require("./lib/components/subHeader.js").subHeader,
	table: require("./lib/components/table"),
	title: require("./lib/components/title.js").title
};
